=== shyti20/esercizi_tpsit_lab/xml/esercizio03/magazzino.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.mysite.com"
    xmlns="https://www.mysite.com"
    elementFormDefault="qualified">

    <xs:element name="magazzino">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="scaffale" type="xs:string"/>
                    <xs:sequence>
                        <xs:element name="prodotto" type="xs:string">
                            <xs:sequence>
                                <xs:element name="nome"> 
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="Acciao" />
                                            <xs:enumeration value="Ferro" />
                                            <xs:enumeration value="Pane" />
                                            <xs:enumeration value="Pomodori" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                   
                                <xs:element name="prezzo_unitario">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:decimal">
                                            <xs:minExclusive value="0" />
                                            <xs:maxExclusive value="1000000000000000000000000000000000000"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>

                                <xs:element name="quantita"> 
                                    <xs:simpleType>
                                        <xs:restriction base="xs:integer">
                                            <xs:maxInclusive value="0" />
                                            <xs:minInclusive vlaue="1000" />
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>

                                
                                <xs:element name="ultimo_ordine" type="xs:date"/>
                            </xs:sequence>
                        </xs:element>
                        </xs:sequence>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== shyti20/esercizi_tpsit_lab/xml/esercizio03/esercizio03.xml
<?xml version="1.0" encoding="UTF-8"?>

<magazzino
    xmlns="https://esercizio03.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://esercizio03.com magazzino.xsd">

        <scaffale id_scaffale="s1312">
            <prodotto id_prodotto="p3231">
                <nome>Acciaio</nome>
                <prezzo_unitario>2.99</prezzo_unitario>
                <quantita>100</quantita>
                <ultimo_ordine>2024-04-20</ultimo_ordine>
            </prodotto>
            <prodotto id_prodotto="p7463">
                <nome>Ferro</nome>
                <prezzo_unitario>1.99</prezzo_unitario>
                <quantita>1000</quantita>
                <ultimo_ordine>2022-10-31</ultimo_ordine>
            </prodotto>
        </scaffale>
        <scaffale id_scaffale="s3234">
            <prodotto id_prodotto="p4738">
                <nome>Pane</nome>
                <prezzo_unitario>1.00</prezzo_unitario>
                <quantita>200</quantita>
                <ultimo_ordine>2006-11-12</ultimo_ordine>
            </prodotto>
            <prodotto id_prodotto="p3778">
                <nome>Pomodori</nome>
                <prezzo_unitario>10.00</prezzo_unitario>
                <quantita>10</quantita>
                <ultimo_ordine>2006-10-30</ultimo_ordine>
            </prodotto>
        </scaffale>
</magazzino>
